version: 2
jobs:
  build:
    working_directory: /go/src/github.com/codercom/retry
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run: go get -u github.com/golang/dep/cmd/dep
      - restore-cache:
          key: dependency-cache-{{ checksum "Gopkg.lock" }}
      - run: dep ensure -v
      - save-cache:
          key: dependency-cache-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run:
          name: Running tests...
          command: "echo 'mode: atomic' > coverage.out && go list ./... | xargs -n1 -I{} sh -c 'go test -race -v -covermode=atomic -coverprofile=coverage.tmp {} && tail -n +2 coverage.tmp >> coverage.out' && rm coverage.tmp"
      - run:
          name: sending to coveralls.io
          command: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
